#!/bin/bash

# shellcheck disable=SC2317
#
# init_server             | By Don! Briggs <DonBriggsWork@gmail.com>
#
# This script will connect to a remote server over SSH, create a 'scripts'
# directory in the user's $HOME directory, and remotely execute the newly
# installed 'init-server' script to configure the server as a Laravel/LAMP
# server.

#TODO Check that required packages are insalled locally
#TODO Check that required files exist in the current directory
#TODO Move verbose param print to its own function. Impliment cli flags

## Connection parameters
uid='ubuntu'
remoteHost="$1"
scriptDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
resourceDir="$scriptDir/resource"
destDir="/home/$uid"


clear
printf "=======================================================================\n"
printf "                        Initializing Remote Server\n"
printf "=======================================================================\n"
printf "      Remote Host:        %s\n" "$remoteHost"
printf "      Remote UID:         %s\n" "$uid"
printf "\n"
printf "      Local Resource Dir: %s\n" "$resourceDir"
printf "      Remote Dest Dir:    %s\n" "$destDir"
printf "\n"
printf "      Script Dir:         %s\n" "$scriptDir"
printf "=======================================================================\n"


  # Create remote 'scripts' directory
if
  ssh "$remoteHost" mkdir /home/"$uid"/scripts 2> /dev/null;
then
   printf "   - Created 'scripts' directory on remote\n"
else
  printf "    - WARNING: Could not create remote directory\n";
fi

  # Copy files to remote host using scp
printf "    - Pushing files to Remote Host: "
if
  scp -r  "$resourceDir"/* "$remoteHost":/home/"$uid"/scripts/ > /dev/null;
then
  printf "[Success]\n"
else
  printf "[FAILURE]\n"
fi
