#!/bin/bash

# shellcheck disable=SC2317
#
# init_server             | By Don! Briggs <DonBriggsWork@gmail.com>
#
# This script will connect to a remote server over SSH, create a 'scripts'
# directory in the user's $HOME directory, and remotely execute the newly
# installed 'init-server' script to configure the server as a Laravel/LAMP
# server.

#TODO Check that required packages are insalled locally
#TODO Check that required files exist in the current directory
#TODO Move verbose param print to its own function. Impliment cli flags

## Connection parameters
uid='ubuntu'
pubDns='ec2-3-91-202-11.compute-1.amazonaws.com'
idFile='wgtmp.pem'
scriptDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
resourceDir="$scriptDir/resource"
destDir="/home/$uid"


clear
printf "=======================================================================\n"
printf "                        Initializing Remote Server\n"
printf "=======================================================================\n"
printf "      Remote Host:        %s\n" "$pubDns"
printf "      Remote UID:         %s\n" "$uid"
printf "      Script Dir:         %s\n" "$scriptDir"
printf "\n"
printf "      Local Resource Dir: %s\n" "$resourceDir"
printf "      Destination Dir:    %s\n" "$destDir"
printf "=======================================================================\n"

  # Create remote 'scripts' directory
ssh -i "$HOME/.ssh/$idFile" "$uid"@"$pubDns" mkdir /home/"$uid"/scripts 2> /dev/null || printf "    WARNING: Could not create remote directory\n"

  # Copy files to remote host using scp
printf "    - Pushing files to Remote Host: "
if
  scp -r -q -i "$HOME/.ssh/$idFile" "$resourceDir"/* "$uid"@"$pubDns":/home/"$uid"/scripts/;
    # 2> /dev/null;
then
  printf "[Success]\n"
else
  printf "[FAILURE]\n"
fi

# printf "    - Running config script on remote server "
# printf "\n\n\n\n\n\n"

# if
  # ssh -i "$HOME/.ssh/$idFile" "$uid"@"$pubDns" "cd scripts && ./init-server";
# then
#       printf "[SUCCESS]\n"
# else
#       printf "[FAILURE]\n"
#       exit 100;
# fi

# printf "\n\n\n\n"