#!/bin/bash
# By: Don! Briggs <donbriggswork@gmail.com>
# apt-upgrade
#
# Update and Upgrade all Ubuntu Sofrware
#

clear
printf "\nPerforming Update and package upgrade\n"
printf "=================================================================\n"
sudo apt autoclean > /dev/null
sudo apt-get update -y > /dev/null
sudo apt-get upgrade
# sudo apt full-upgrade -y
sudo apt autoremove -y