#!/bin/bash

#
# init_server             | By Don! Briggs <DonBriggsWork@gmail.com>
#
# This script will make an attempt to configure a newly instaled Ubuntu
# server as LAMP server, with apache support.
#

#TODO Chek that required files exist in the current directory

export TERM='xterm'

clear
printf "\n"
printf "======================================================================\n"
printf "                   Initializing LAMP/Laravel Server\n"
printf "======================================================================\n"
# echo $(pwd);
# cd ~/scripts || printf "ERROR: Could not cd to 'scripts'\n" && exit 100

printf "    - Installing 'bash_aliases\n"
# cp bash_aliases "$HOME/.bash_aliases" || printf "ERROR: Could not copy bash aliases\n" && exit 105
# printf "    - Installing '.profile\n"
# mv "$HOME/.profile" profile.bak || printf "ERROR: Could not backup '.bash_aliases'\n" && exit 110
# cp profile "$HOME/.profile"|| printf "ERROR: Could not create '.bash_aliases'\n" && exit 115
# source "$HOME/.profile"

printf "    - Updating Sysyem\n"
apt_upg
#  inst_lamp
#  wwwperms
# inst_composer
# inst_laravel
printf "======================================================================\n\"