#!/bin/bash

# inst_laravel    By: Don! Briggs  <DonBriggsWork@gmail.com>
#
# Install the Laravel Development Framework on a Ubuntu based Linux
# host. This script depends on the 'inst_lamp' script which will
# install the LAMP stack.It will also create a default Laravel web site and Apache virtual
# host. The Laravel site is created in: "/var/www/laravel"

clear
printf "\n      -- Configuring Laravel via Composer\n"
printf "_______________________________________________________\n\n"

#TODO Check that composer exists, install if not
wwwperms

# sudo rm -rf /var/www/html || exit 120
composer create-project --prefer-source laravel/laravel /var/www/laravel || printf "ERROR: Could not create composer project\n" && exit 121

sudo cp laravel.conf /etc/apache2/sites-available || printf "ERROR: Could noy create Apache configuration file\n" && exit 122
sudo a2ensite laravel.conf || printf "ERROR: Could not enable Laravel site\n" && exit 123
sudo systemctl restart apache2 || printf "ERROR: Could not restart Apache server\n" && exit 124
wwwperms